name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: pull sources
      run: git pull https://github.com/jbonachera/hello-world.git
    - name: Build the Docker image
      run: docker build hello-world --file Dockerfile --tag my-image-name:$(date +%s)
