name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:

env:
  TAG: v4.0.${{ github.run.id }}

jobs:

  prepare:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        repository: jbonachera/hello-world
        ref: master
        path: hello-world
        
    - name: Upload a Sources
      uses: actions/upload-artifact@v2.2.4
      with:
        name: hello-world
        path: .
  
  front:
    runs-on: ubuntu-latest
    needs: prepare
    
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.0.10
      with:
        name: hello-world
    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
        username: neolutin
        password: ${{ secrets.DOCKERHUB }}
        logout: true
  
    - name: Build the OCI image
      run: docker build hello-world --file front/Dockerfile --tag cactus-front:${{ env.TAG }}

    - name: Push the OCI image
      run: docker push neolutin/cactus-front:${{ env.TAG }}
  
  back:
    runs-on: ubuntu-latest
    needs: prepare
    
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.0.10
      with:
        name: hello-world
    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
        username: neolutin
        password: ${{ secrets.DOCKERHUB }}
        logout: true
  
    - name: Build the OCI image
      run: docker build hello-world --file back/Dockerfile --tag cactus-back:${{ env.TAG }}

    - name: Push the OCI image
      run: docker push neolutin/cactus-back:${{ env.TAG }}
  
