name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        repository: jbonachera/hello-world
        ref: master
        path: hello-world

    - name: Build the Docker image
      run: docker build hello-world --file Dockerfile --tag my-image-name:$(date +%s)
